### ISSUE TITLE
Change the color of the progression bar.

### ISSUE THREAD

**Issue by PrithirajN** [qms-apps/Pluma-Android-Issue-Tracker#4]
I think the colour of the reading progression bar would look more cool if it matches with the accent color.

**Comment by qijaz221** [comment]
Only issue with that is that it might get harder to distinguish between a link and progress bar because then both are going to be the same color. As you can see in the screenshot below, though here they are not exactly the same color but it's still a bit hard to tell them apart at first glance. 

![Screenshot_20210305-201343](https://user-images.githubusercontent.com/9846942/110134973-d0e11600-7def-11eb-816f-a12ba6d16ca4.png)

**Comment by PrithirajN** [comment]
Ok now I see the problem.
